<a href="https://colab.research.google.com/github/maqsoodahmadkhan3982-dotcom/Materials-Properties-Response/blob/main/System_of_Linear_Equations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Solution of System of Linear Equations using Augmented Matrix

In [ ]:
a=[1,2,3]
print(2*a)

[1, 2, 3, 1, 2, 3]


In [ ]:
b=[4,5,6]
print(a+b)

[1, 2, 3, 4, 5, 6]


In [ ]:
import numpy as np
a1=np.array([1,2,3])
b1=np.array([4,5,6])
print(2*a1)
print(a1+b1)
print(b1-4*a1)

[2 4 6]
[5 7 9]
[ 0 -3 -6]


In [ ]:
import numpy as np
A1=np.array([1,2,3])
print(f'The 1st Element of A1 is {A1[0]}')


The 1st Element of A1 is 1


In [ ]:
import numpy as np
A1=np.array([1,2,3])
for i in range(1,3):
    print(f'{i} Element of A1 is {A1[i]}')
print("\n\n\n")
for i in range(len(A1)):
    print(f'{i} Element of A1 is {A1[i]}')

1 Element of A1 is 2
2 Element of A1 is 3




0 Element of A1 is 1
1 Element of A1 is 2
2 Element of A1 is 3


In [ ]:
# Problem: Solve the system 5x+3y=3;    2x-y=4
# The Augmented Matrix of the system is
import numpy as np
Ag=np.array([[5, 3, 3],
            [2,-1,4]])
# R1-2R2
print(Ag)

Ag1=np.array([Ag[0]-2*Ag[1],Ag[1]])
print(Ag1)

[[ 5  3  3]
 [ 2 -1  4]]
[[ 1  5 -5]
 [ 2 -1  4]]


In [ ]:
# R2-2R1
Ag2=np.array([Ag1[0],Ag1[1]-2*Ag1[0]])
print(Ag2)


[[  1   5  -5]
 [  0 -11  14]]


In [ ]:


# -1/11*R2
Ag2=np.array([Ag1[0],Ag1[1]-2*Ag1[0]])
print(Ag2)

Ag3=np.array([Ag2[0],-1/11*Ag2[1]])
print(Ag3,'\n')

# R1-R2
Ag4=np.array([Ag3[0]-5*Ag3[1],Ag3[1]])
print(Ag4)

print('The Solution is given by',f'\nx={Ag4[0][2]},y={Ag4[1][2]}')

[[  1   5  -5]
 [  0 -11  14]]
[[ 1.          5.         -5.        ]
 [-0.          1.         -1.27272727]] 

[[ 1.          0.          1.36363636]
 [-0.          1.         -1.27272727]]
The Solution is given by 
x=1.3636363636363633,y=-1.2727272727272727


# Problem: Solve the system 5x+3y=3;    2x-y=4
# The Augmented Matrix of the system is

In [ ]:
import numpy as np
Ag=np.array([[5, 3, 3],
               [2,-1,4]])
# R1-2R2
Ag1=np.array([Ag[0]-2*Ag[1],Ag[1]])
print(Ag1)

[[ 1  5 -5]
 [ 2 -1  4]]


In [ ]:
# R2-2R1
Ag2=np.array([Ag1[0],Ag1[1]-2*Ag1[0]])
print(Ag2)

[[  1   5  -5]
 [  0 -11  14]]


In [ ]:
# -1/11*R2

Ag3=np.array([Ag2[0],-1/11*Ag2[1]])
print(Ag3)

[[ 1.          5.         -5.        ]
 [-0.          1.         -1.27272727]]


In [ ]:
# R1-R2
Ag4=np.array([Ag3[0]-5*Ag3[1],Ag3[1]])
print(Ag4)

[[ 1.          0.          1.36363636]
 [-0.          1.         -1.27272727]]


In [ ]:
print('The Solution is given by',f'\nx={Ag4[0][2]},y={Ag4[1][2]}')

The Solution is given by 
x=1.3636363636363633,y=-1.2727272727272727


In [ ]:
print('The Solution is given by gsgd',f'\nx={Ag4[0,2]},y={Ag4[1,2]}')

The Solution is given by gsgd 
x=1.3636363636363633,y=-1.2727272727272727


In [ ]:
# Using function rref from sympy
import sympy as sp
Ag=sp.Matrix([[5, 3, 3],
            [2,-1,4]])
Ag, pivot_columns=Ag.rref()
print(Ag)
print('The Solution is given by',f'\nx={Ag.row(0)[2]},y={Ag.row(1)[2]}')

print(f'The Solution is given by \n x={Ag.row(0)[2]},y={Ag.row(1)[2]}')

print(f'The pivot columns are {pivot_columns}')

print(f'The Rank of Ag={len(pivot_columns)}')

Matrix([[1, 0, 15/11], [0, 1, -14/11]])
The Solution is given by 
x=15/11,y=-14/11


In [ ]:
# Using function rref from sympy
import sympy as sp
Ag=sp.Matrix([[5, 3, 3],
            [2,-1,4]])
Ag, pivot_columns=Ag.rref()
Ag=np.array(Ag)                      #Converting a unmutable object that is tuple into a List, a mutable object
Ag=Ag.astype(float)                 #Changing type of data so that we can get results in decimal form
print(Ag)
print('The Solution is given by',f'\nx={Ag[0][2]},y={Ag[1][2]}')

NameError: name 'np' is not defined

In [ ]:
A=np.array([[5,3],
            [2,-1]])
B=np.array([3,4])
X=np.linalg.solve(A,B)                         # Use of Linear Algebra module in numpy to solve system Ax=B
print('The solution of the system is (x,y)=',X)

The solution of the system is (x,y)= [ 1.36363636 -1.27272727]


# System of Three Linear Equations Linear System:

#  x-y+2z=5

# 2x-2y+4z=10

# 3x-3y+6z=15

In [ ]:
A=np.array([[1,1,2],[2,8,10],[3,7,6]])
B=np.array([5,0,15])
X=np.linalg.solve(A,B)
print('The solution of the system is (x,y,z)=',X)

The solution of the system is (x,y,z)= [ 8.33333333e+00  5.32907052e-16 -1.66666667e+00]


In [ ]:
Ag=np.array([[1,-1,2,5],[2,-2,4,10],[3,-3,6,15]])

Ag=np.array([Ag[0],Ag[1]-2*Ag[0],Ag[2]-3*Ag[0]])
print(Ag)


[[ 1 -1  2  5]
 [ 0  0  0  0]
 [ 0  0  0  0]]


In [ ]:
import sympy as sp
Ag=sp.Matrix([[1,-1,2,5],[2,-2,4,10],[3,-3,6,15]])
Ag, pivot_columns=Ag.rref()
print(Ag)
print(f'The pivot columns are {pivot_columns}')

print(f'The Rank of Ag={len(pivot_columns)}')

print(f'Total number of free variables are {len(Ag.row(0))-1-len(pivot_columns)}')

Matrix([[1, -1, 2, 5], [0, 0, 0, 0], [0, 0, 0, 0]])
The pivot columns are (0,)
The Rank of Ag=1
Total number of free variables are 2


# The above matrix shows that only first colomn is pivot colomn. Therefore, y and z are free variables. So x will be expressed in terms of y and z

In [ ]:
def x(y,z):
    return 5+y-2*z
y=input('Substitute the vaue of y')
z=input('Substitute the value of z')
print('The solution of the system is (x,y,z)=',(x(y,z),y,z))

Substitute the vaue of y1
Substitute the value of z2


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
def x(y,z):
    return 5+y-2*z
y=float(input('Substitute the vaue of y'))
z=float(input('Substitute the value of z'))
print('The solution of the system is (x,y,z)=',(x(y,z),y,z))

Substitute the vaue of y1
Substitute the value of z-5
The solution of the system is (x,y,z)= (16.0, 1.0, -5.0)


In [ ]:
print(f'Problem:Solve the system \nx+y+2z=9 \n2x+4y-3z=1 \n3x+6y-5z=0')

In [ ]:
Ag=np.array([[1,1,2,9],[2,4,-3,1],[3,6,-5,0]])
Ag=np.array([Ag[0],Ag[1]-2*Ag[0],Ag[2]-3*Ag[0]])
print(Ag)

NameError: name 'np' is not defined

In [ ]:
Ag=np.array([Ag[0],1/2*Ag[1],Ag[2]])
Ag=np.array([Ag[0]-Ag[1],Ag[1],Ag[2]-3*Ag[1]])
print(Ag)

In [ ]:
Ag=np.array([Ag[0],Ag[1],-2*Ag[2]])
Ag=np.array([Ag[0]-5.5*Ag[2],Ag[1]+3.5*Ag[2],Ag[2]])
print('Augmented Matrix in Reduced Echelon Form is \n',Ag)
print('The Solution is given by',f'\nx={Ag[0][3]},y={Ag[1][3]},z={Ag[2][3]}')

NameError: name 'np' is not defined

In [ ]:
import sympy as sp
import numpy as np
Ag=sp.Matrix([[1,1,2,9],[2,4,-3,1],[3,6,-5,0]])
RREF,Pivot=Ag.rref()
AG=np.array(RREF)
print('The Row Reduced Echelon Form of Augmented Matrix is:',f'\n{RREF}')
print('The Augmented matrix as an array is ',f'\n{AG}')
print('The Solution is given by',f'\nx={AG[0][3]},y={AG[1][3]},z={AG[2][3]}')
print('The Pivot columns are: \n',np.array(Pivot))

In [ ]:
# Problem: a+b+c=1,   4a+2b+c=4,    a-b+c=1
Ag=np.array([[1,1,1,1],[4,2,1,4],[1,-1,1,1]])

Ag=np.array([Ag[0],Ag[1]-4*Ag[0],Ag[2]-Ag[0]])
print(Ag)

In [ ]:
Ag=np.array([Ag[0],-1/2*Ag[2],-Ag[1]])
print(Ag)

In [ ]:
Ag=np.array([Ag[0]-Ag[1],Ag[1],Ag[2]-2*Ag[1]])
print(Ag)

In [ ]:
Ag=np.array([Ag[0],Ag[1],1/3*Ag[2]])
print(Ag)

In [ ]:
Ag=np.array([Ag[0]-Ag[2],Ag[1],Ag[2]])
print(Ag)

In [ ]:
I=np.array([[1,0,0],[0,1,0],[0,0,1]])
I=np.array([I[0],I[1]-4*I[0],I[2]-I[0]])
print(I)

In [ ]:
I=np.array([I[0],-1/2*I[2],-I[1]])
print(I)

In [ ]:
I=np.array([I[0]-I[1],I[1],I[2]-2*I[1]])
print(I)

In [ ]:
I=np.array([I[0],I[1],1/3*I[2]])
print(I)

In [ ]:
I=np.array([I[0]-I[2],I[1],I[2]])
print(I)

In [ ]:
import sympy as sp


I = sp.Matrix(I)                                         # Define a matrix with floating-point entries


I_as_fractions = I.applyfunc(sp.nsimplify)             # Convert floating-point entries to fractions

I1=np.array(I_as_fractions)

print(I_as_fractions ,'\n')
print(I1,'\n')

NameError: name 'I' is not defined

In [ ]:
# Using Linalgebra Package
P=np.linalg.multi_dot([np.array([[1,1,1],[4,2,1],[1,-1,1]]),I1])
print(P)
#print(np.abs(np.round(P)))

In [ ]:
# Using Linalgebra Package
P1=np.linalg.multi_dot([np.array([[1,1,1],[4,2,1],[1,-1,1]]),np.array([[-1/2,1/3,1/6],[1/2,0,-1/2],[1,-1/3,1/3]])])
print(P1)
#print(np.abs(np.round(P)))

In [ ]:
# Using Only Numpy
P=np.dot(np.array([[1,1,1],[4,2,1],[1,-1,1]]),np.array([[-1/2,1/3,1/6],[1/2,0,-1/2],[1,-1/3,1/3]]))
print(np.abs(np.round(P)))

In [ ]:
np.linalg.det(np.array([[1,0,0],[0,1,0],[0,0,1]]))

In [ ]:
np.linalg.inv(np.array([[1,1,1],[4,2,1],[1,-1,1]]))

NameError: name 'np' is not defined